require 'sidekiq'
require 'sidekiq/web'

# TODO : decide how to pass ENV['REDIS_URL'].

Sidekiq.remove_delay!

Sidekiq.configure_server do |config|
  #config.redis = { url: "#{ENV['REDIS_URL']}/0" }
  config.redis = { url: "redis://localhost:6379/0" } # this is a temporal trick while we decide how to pass ENV['REDIS_URL']
  config.average_scheduled_poll_interval = 1 # instead of 15 seconds by  default
end

Sidekiq.configure_client do |config|
  #config.redis = { url: "#{ENV['REDIS_URL']}/0" }
  config.redis = { url: "redis://localhost:6379/0" } # this is a temporal trick while we decide how to pass ENV['REDIS_URL']
end

Sidekiq::Web.set :sessions, false # disable any sessions creation in sinatr and rely entirely on the session generated by rails